cpp:
  cluster:
    properties: {
        a: a
    }
    name: SimpleCluster
    master:
      name: Test-Master
      netty:
        host: 0.0.0.0
        port: 10089
    worker:
      name: Test-Worker








